In [2]:
import pandas as pd
import seaborn as sns
import re
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import sys
from matplotlib import font_manager, rc, cm                ## 폰트를 관리하는 함수와 설정 함수를 사용한다. 

font_path = './font/GmarketSansTTFMedium.ttf'
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

In [3]:
df1 = pd.read_excel('./data/2021년 01월 시군구별_용도별 건축허가현황.xlsx', engine='openpyxl', header=1)
df1.drop(index=[0,3,30,42], inplace=True)
df1.set_index('구분', inplace=True)
df1_1 = df1[['Unnamed: 1', '전체용도 합계']]
df1_1.drop(['전국(전체)','서울특별시(전체)','인천광역시(전체)','경기도(전체)'],axis=0, inplace=True)
df1_1.rename(columns={'Unnamed: 1':'지 역'}, inplace=True)
df1_1

C:\Users\User\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\User\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

        지 역  전체용도 합계
구분
서울      강동구  20057.0
서울      강북구  13488.0
서울      강서구  73003.0
서울      관악구  22629.0
서울      광진구  40267.0
..      ...      ...
경기  안양시 동안구   1993.0
경기  안양시 만안구   4447.0
경기  용인시 기흥구   9302.0
경기  용인시 수지구   6392.0
경기  용인시 처인구  32770.0

[80 rows x 2 columns]